config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get :floors, to: "pages#floors"
  get :user_infos, to: "pages#user_infos"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meetings, only: [:index, :new, :create, :show, :update, :edit] do
    resources :decisions, only: [:new, :create, :index]
    resources :documents, only: [:new, :create, :index, :show]
    member do
      get :show_pdf
    end
  end

  resources :decisions, only: [:show, :update, :edit] do
    member do
      post :vote
      patch :open
      patch :close
    end

    resources :documents, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :documents, only: [:index, :show, :new, :create]

  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :chat_members, only: [:create]
    resources :messages, only: [:create]
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user
  belongs_to :coproperty
  has_many :documents, as: :documentable
  has_many :decisions
  after_touch :broadcast_vote

  attr_accessor :document_name, :document_tag

  def over?
    # decisions.all? { |decision| decision.closed? }
    decisions.present? && decisions.all?(&:closed?)
  end

  private

  def broadcast_vote
    binding.pry
    decision = decisions.find_by(status: :opened)
    broadcast_replace dom_id(@meeting),
                        partial: "decisions/vote",
                        target: dom_id(@meeting),
                        locals: { decision: decision }
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :update, :edit, :show_pdf]

  def index
    @meetings = Meeting.all
    @title = "Mes réunions"
  end

  def show_pdf
    render pdf: "compte_rendu_#{@meeting.title.gsub(" ", "_")}",
           template: "meetings/show_pdf",
           layout: "pdf"

  end

  def show
    # @decisions = @meeting.decisions # - @meeting.decisions.joins(:votes).where(user: current_user).uniq
    @title = @meeting.title
    @document = Document.new
    @decision = Decision.new
  end

  def new
    @meeting = Meeting.new
    @document = Document.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = current_user
    @meeting.coproperty_id = current_user.coproperty_id
    if @meeting.save
      @document = Document.create!(
        name: document_params[:document_name],
        tag: document_params[:document_tag],
        file: document_params[:file],
        user: current_user,
        coproperty: current_user.coproperty
      )
      @meeting.documents << @document
      redirect_to meeting_path(@meeting)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
  end

  def update
    if @meeting.update(meeting_params)
    redirect_to meeting_path(@meeting), notice: "Meeting mise à jour."

    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :date, :link, :description)
  end

  def document_params
    params.require(:meeting).permit(:file, :document_tag, :document_name)
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end
end

app/views/meetings/_decision.html.erb
<div class="pt-2 pb-3 d-flex gap-2 justify-content-between align-items-left flex-column separator">

  <div class="d-flex align-items-left flex-column gap-3">
    <div class="flex-grow-1 d-flex align-items-center">
      <%= image_tag "gavel.png", width: 30, height: 30, class: "me-2" %>
      <%= link_to decision_path(decision), class: "text-decoration-none" do %>
      <p class="mb-0 me-2"><%= decision.title %></p>
      <% end %>
    </div>
    <% if decision.pending? %>
      <%= link_to "Ouvrir le vote", open_decision_path(decision),
        class: "show-btn fs-6 d-none",
        data: {
          turbo_method: :patch,
          meeting_target: "adminBtn"
        } %>
    <% elsif decision.opened? %>
      <%= link_to "Clôturer le vote", close_decision_path(decision),
        class: "show-btn fs-5 d-none",
        data: {
          turbo_method: :patch,
          meeting_target: "adminBtn"
          } %>
    <% end %>
  </div>

  <% if decision.closed? %>
    <%= render "decisions/result", decision: decision %>
  <% end %>
</div>

app/views/meetings/_over_show.html.erb
<div id="<%= dom_id(meeting) %>" class="container mt-5 justify-content-center">

      <div class="show-card-header mb-3">
        <h4 class=""><strong>Informations </strong></h4>
      </div>
      <div class="px-3">
        <p><i><%= l(meeting.date, format: :long) %></i></p>
        <p><%= meeting.link %></p>
        <p><%= meeting.description %></p>
      </div>

  <div class="d-flex flex-column gap-4" data-controller="vote">
    <div class="show-card py-3 mt-3 mb-3">
      <div class="show-card-header mb-3">
        <h4 class=""><strong>Décisions</strong></h4>
      </div>
      <div class="px-3 d-flex flex-column gap-2">
        <% meeting.decisions.each do |decision| %>
          <%= render "meetings/decision", decision: decision %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="show-card mt-3 py-3 mb-3">
    <div class="show-card-header mb-3">
      <h4 class=""><strong>Documents</strong></h4>
    </div>

      <div class="px-3">
        <% if meeting.documents.any? %>
          <% meeting.documents.each do |document| %>
          <div class=" p-2 d-flex justify-content-between align-items-left flex-column">
            <div class="lien">
              <%= link_to document_path(document), class: "text-decoration-none d-flex align-items-center mb-1"  do %>
                <%= image_tag "document_icone.png", width: 30, height: 30, class: "me-2" %>
                <p class="mb-0 me-2"><%= document.name %></p>
              <% end %>
              </div>
            </div>

          <% end %>
        <% end %>
        <div class="d-flex justify-content-center mt-3">
        <%= link_to "Télécharger le compte rendu de réunion", show_pdf_meeting_path(meeting), class:"show-btn" %>
      </div>
      </div>
  </div>
</div>

app/views/meetings/_show.html.erb
<div id="<%= dom_id(meeting) %>" class="container mt-5 justify-content-center">

      <div class="show-card-header mb-3">
        <h4 class=""><strong>Informations </strong></h4>
      </div>
      <div class="px-3">
        <p><i><%= l(meeting.date, format: :long) %></i></p>
        <p><%= meeting.link %></p>
        <p><%= meeting.description %></p>
      </div>

  <div class="d-flex flex-column gap-4" data-controller="vote">
  <div class="show-card py-3 mb-3 position-relative">
    <div class="show-card-header mb-3">
      <h4 class=""><strong>Décisions</strong></h4>
      <button type="button" class="modal-btn p-0" data-bs-toggle="modal" data-bs-target="#exampleModal">
         <p class="button-plus-right">+</p>
      </button>
      <%= render "/decisions/form", meeting: meeting, decision: decision %>
    </div>
    <div class="px-3 d-flex flex-column gap-2">
      <% meeting.decisions.each do |decision| %>
        <%= render "meetings/decision", decision: decision %>
      <% end %>
  </div>
</div>
</div>


  <div class="show-card mt-3 py-3 mb-3 position-relative">
    <div class="show-card-header mb-3 ">
      <h4 class=""><strong>Documents</strong></h4>
      <%= link_to "+", new_meeting_document_path(meeting), class:"button-plus-right"%>
    </div>
  <div class="px-3">
    <% if meeting.documents.any? %>
      <% meeting.documents.each do |document| %>
      <div class=" p-2 d-flex justify-content-between align-items-left flex-column ">
        <div class="lien ">
          <%= link_to document_path(document), class: "text-decoration-none d-flex align-items-center mb-1" do %>
            <%= image_tag "document_icone.png", width: 30, height: 30, class: "me-2 " %>
            <p class="mb-0 me-2 "><%= document.name %></p>
          <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>


</div>

app/views/meetings/edit.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class = "card border-0 rounded shadow-lg p-4" style="max-width: 700px; width: 100%;">

  <h2 class="text-center" style = "color: #595959;">Modifier votre réunion</h2>
    <%= simple_form_for [@meeting] do |f| %>
      <div class="form-group mb-3">
        <%= f.input :title, label: "Titre" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :description, label: "Description" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :link, label: "Lien" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :date, label: "Date" %>
      </div>
      <div class="d-flex justify-content">
        <%= f.submit "Submit", class: "button-card" %>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/index.html.erb
<div class= "button-plus">
<%= link_to new_meeting_path, style: "text-decoration: none;" do %>
  <p style="
    font-size: 60px;
    color: white;
    margin: 0;">+</p>
    <% end %>
</div>

<div class="container mt-5">
  <div class="row justify-content-evenly g-3 mt-3">
    <% @meetings.each do |meeting| %>
      <%= link_to meeting_path(meeting), class: "text-decoration-none" do %>
        <div class="document-affichage">
          <div class="document-icon">
            <i class="fa-regular fa-handshake"></i>
            </div>
          <div class="document-name">
            <p><%= meeting.title %></p>
            <p style="font-size: 11px"><i><%= l(meeting.date, format: :long) %></i></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class = "card border-0 rounded shadow-lg p-4" style="max-width: 700px; width: 100%;">

  <h2 class="text-center" style = "color: #595959;">Créer une réunion</h2>
    <%= simple_form_for [@meeting] do |f| %>
      <div class="form-group mb-3">
        <%= f.input :title, label: "Titre" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :description, label: "Description" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :link, label: "Lien" %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
      </div>
      <div class="form-group mb-3">
        <%= f.input :file, as: :file, label: "Document" %>
      </div>

      <div class="form-group mb-3">
        <%= f.input :document_name, label: "Nom document" %>
      </div>

      <div class="form-group mb-3">
        <%= f.input :document_tag, label: "Tag document" %>
      </div>

      <div class="d-flex justify-content">
        <%= f.submit "Submit", class: "button-card" %>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/show.html.erb
<% if @meeting.over? %>

  <%= render "meetings/over_show", meeting: @meeting %>

<% else %>

  <%= turbo_stream_from dom_id(@meeting) %>

  <div data-controller="meeting"
    data-meeting-is-admin-value="<%= current_user.status %>">
    <%= render "meetings/show", meeting: @meeting, decision: @decision %>
  </div>

<% end %>

app/views/meetings/show_pdf.html.erb
<%= render "meetings/over_show", meeting: @meeting %>