config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get :floors, to: "pages#floors"
  get :user_infos, to: "pages#user_infos"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meetings, only: [:index, :new, :create, :show, :update, :edit] do
    resources :decisions, only: [:new, :create, :index]
    resources :documents, only: [:new, :create, :index, :show]
    member do
      get :show_pdf
    end
  end

  resources :decisions, only: [:show, :update, :edit] do
    member do
      post :vote
      patch :open
      patch :close
    end

    resources :documents, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :documents, only: [:index, :show, :new, :create]

  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :chat_members, only: [:create]
    resources :messages, only: [:create]
  end
end

app/models/decision.rb
class Decision < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user
  belongs_to :meeting #, touch: true
  has_many :documents, as: :documentable
  has_many :votes

  after_save :broadcast_vote, if: :opened?
  after_save :broadcast_meeting, if: :closed?


  enum :status, {
    pending: 0,
    opened: 1,
    closed: 2
  }


  attr_accessor :document_name, :document_tag


  def already_voted_by?(user)
    self.votes.find_by(user: user).present?
  end

  def vote_of(user)
    self.votes.find_by(user: user)
  end

  def for
    self.votes.where(value: true).count
  end

  def against
    self.votes.where(value: false).count
  end

  private

  def broadcast_vote
    broadcast_replace_to dom_id(self.meeting),
                        partial: "decisions/vote",
                        target: dom_id(self.meeting),
                        locals: { decision: self }
  end

  def broadcast_meeting
    partial_path = meeting.over? ? "meetings/over_show" : "meetings/show"
    broadcast_replace_to dom_id(self.meeting),
                        partial: partial_path,
                        target: dom_id(self.meeting),
                        locals: { meeting: self.meeting }
  end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: [:show, :edit, :update, :close, :vote, :open]
  before_action :authenticate_user!, only: [:create, :update]

  def index
    @meeting = Meeting.find(params[:meeting_id])
    @decisions = @meeting.decisions
  end

  def show
  end

 def new
  @meeting = Meeting.find(params[:meeting_id])
  @decision = Decision.new
  @document = Document.new
  @title = "Créer une décision"
 end

 def create
  @meeting = Meeting.find(params[:meeting_id])
  @decision = Decision.new(decision_params)
  @decision.user = current_user
  @decision.meeting = @meeting
  if @decision.save
    if document_params[:file]
      @document = Document.create!(
        name: document_params[:document_name],
        tag: document_params[:document_tag],
        file: document_params[:file],
        user: current_user,
        coproperty: current_user.coproperty
      )
      @decision.documents << @document
    end
    redirect_to meeting_path(@meeting)
  else
    render :new, status: :unprocessable_entity
  end
 end


  def edit
  end

  def update
    if @decision.update(decision_params)
      redirect_to decision_path(@decision), notice: "Décision mise à jour."
    else
      render :edit
    end
  end

  def close
    result = @decision.votes.where(value: true).count > @decision.votes.where(value: false).count
    @decision.accepted = result
    @decision.closed!
    # Pas de render ou de redirect car un stream actualise la page
  end

  def open
    @decision.opened!
    # Pas de render ou de redirect car un stream actualise la page
  end

  def vote
    @vote = Vote.new(value: params[:vote_value] == "for")
    @vote.user = current_user
    @vote.decision = @decision
    @vote.save
        flash[:notice] = "Votre vote a été pris en compte."

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def decision_params
    params.require(:decision).permit(:title, :description)
  end

   def document_params
    params.require(:decision).permit(:file, :document_tag, :document_name)
   end

   def set_decision
     @decision = Decision.find(params[:id])
   end
end

app/views/decisions/_form-vote.html.erb
<div class="modal fade" id="voteModal" tabindex="-1" aria-labelledby="voteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% total_votes = @decision.votes.count.to_f %>
        <% pourcentage_pour = total_votes.zero? ? 0 : ((@decision.votes.where(value: true).count / total_votes) * 100).round %>
        <% pourcentage_contre = total_votes.zero? ? 0 : ((@decision.votes.where(value: false).count / total_votes) * 100).round %>

        <% if @decision.already_voted_by?(current_user) || @decision.closed? %>
          <div data-vote-target="voteSection">
            <div><span></span> <span><%= @decision.votes.where(value: true).count %></span> pour</div>
            <div><span></span> <span><%= @decision.votes.where(value: false).count %></span> contre</div>
          </div>

          <div class="progress mt-2">
            <div class="progress-bar bg-success" role="progressbar"
                 style="width: <%= pourcentage_pour %>%;"
                 aria-valuenow="<%= pourcentage_pour %>"
                 aria-valuemin="0"
                 aria-valuemax="100">
              <%= pourcentage_pour %>% Pour
            </div>
            <div class="progress-bar bg-danger" role="progressbar"
                 style="width: <%= pourcentage_contre %>%;"
                 aria-valuenow="<%= pourcentage_contre %>"
                 aria-valuemin="0"
                 aria-valuemax="100">
              <%= pourcentage_contre %>% Contre
            </div>
          </div>

          <div class="d-flex gap-2 mt-2">
            <% if @decision.vote_of(current_user).value %>
              <span class="text-success">Vous avez voté "pour".</span>
            <% else %>
              <span class="text-danger">Vous avez voté "contre".</span>
            <% end %>
          </div>

        <% else %>
          <div class="d-flex gap-2 mt-2">
            <%= link_to "Pour", decision_votes_path(@decision, value: true), data: { turbo_method: :post }, class: "btn btn-success" %>
            <%= link_to "Contre", decision_votes_path(@decision, value: false), data: { turbo_method: :post }, class: "btn btn-danger" %>
          </div>
        <% end %>

        <% if current_user.status == true && @decision.opened? %>
          <%= link_to "Clôturer le vote", close_decision_path(@decision), class: "btn btn-primary", data: { turbo_method: :patch } %>
        <% end %>

        <% if @decision.closed? %>
          <div data-vote-target="resultSection" class="mt-3">
            <% total_pour = @decision.for %>
            <% total_contre = @decision.against %>
            <div class="d-flex justify-content-between align-items-center gap-3 position-relative">
              <% if total_pour > total_contre %>
                <h3 class="mb-0 w-100"><span class="w-100 badge bg-success">Acceptée</span></h3>
                <% if total_contre == 0 %>
                  <div class="pie" style="background: conic-gradient(#1EDD88 0% 100%,#1EDD88 100%);"></div>
                <% else %>
                  <div class="pie" style="background: conic-gradient( #1EDD88 0% <%= (total_pour/(total_contre+total_pour).to_f)*100 %>%, #FD1015 <%= (total_contre/(total_contre+total_pour).to_f)*100 %>% 100%);"></div>
                <% end %>
              <% elsif total_contre > total_pour %>
                <h3 class="mb-0 w-100"><span class="w-100 badge bg-danger">Rejetée</span></h3>
                <% if total_pour == 0 %>
                  <div class="pie" style="background: conic-gradient(#FD1015 0% 100%,#FD1015 100%);"></div>
                <% else %>
                  <div class="pie" style="background: conic-gradient( #1EDD88 0% <%= (total_pour/(total_contre+total_pour).to_f)*100 %>%,#FD1015 <%= (total_pour/(total_contre+total_pour).to_f)*100 %>% 100%);"></div>
                <% end %>
              <% else %>
                <h3 class="mb-0 w-100"><span class="w-100 badge bg-info text-dark">Egalité</span></h3>
                <div class="pie" style="background: conic-gradient(#1EDD88 0% 50%,#FD1015 50% 100%);"></div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/decisions/_form.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Créer une decision</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <%= simple_form_for [meeting, Decision.new] do |f| %>
          <div class="card-body">
            <div class="row">
             <div class="col">
              <%= f.input :title, label: "Titre" %>
            </div>
              <div class="form-group mb-3">
              <%= f.input :description, label: "Description" %>
            </div>
            <div class="form-group mb-3">
              <%= f.input :file, as: :file, label: "Document" %>
            </div>
            <div class="form-group mb-3">
              <%= f.input :document_name, label: "Nom document" %>
            </div>

            <div class="d-flex justify-content" style= "width: 100%;" >
              <%= f.submit "Ajouter", class: "show-btn show-btn:focus show-btn:hover"%>
            </div>
          <% end %>
            </div>
          </div>
      </div>
      </div>
    </div>
  </div>

app/views/decisions/_result.html.erb
<div data-vote-target="resultSection"
  class=""
  id="<%= dom_id(decision) %>_result">
  <% total_pour = decision.for %>
  <% total_contre = decision.against %>
  <%# <div class="pie three"></div> %>
  <div class="d-flex justify-content-between align-items-center gap-3 position-relative">
    <% if total_pour > total_contre %>
      <h3 class="mb-0 w-100"><span class="w-100 badge bg-success">Acceptée</span></h3>
      <% if total_contre == 0 %>
        <div class="pie" style="background: conic-gradient(#1EDD88 0% 100%,#1EDD88 100%);"></div>
      <% else %>
        <div class="pie" style="background: conic-gradient( #1EDD88 0% <%= (total_pour/(total_contre+total_pour).to_f)*100 %>%, #FD1015 <%= (total_contre/(total_contre+total_pour).to_f)*100 %>% 100%);"></div>
      <% end %>
    <% elsif total_contre > total_pour %>
      <h3 class="mb-0 w-100"><span class="w-100 badge bg-danger">Rejetée</span></h3>
      <% if total_pour == 0 %>
        <div class="pie" style="background: conic-gradient(#FD1015 0% 100%,#FD1015 100%);"></div>
      <% else %>
        <div class="pie" style="background: conic-gradient( #1EDD88 0% <%= (total_pour/(total_contre+total_pour).to_f)*100 %>%,#FD1015 <%= (total_pour/(total_contre+total_pour).to_f)*100 %>% 100%);"></div>
      <% end %>
    <% else %>
      <h3 class="mb-0 w-100"><span class="w-100 badge bg-info text-dark">Egalité</span></h3>
      <div class="pie" style="background: conic-gradient(#1EDD88 0% 50%,#FD1015 50% 100%);"></div>
    <% end %>
  </div>
</div>

app/views/decisions/_vote.html.erb
<%= turbo_stream_from dom_id(decision) %>
<div class="container mt-5 justify-content-center" id="<%= dom_id(decision.meeting) %>">
  <div class="d-flex flex-column gap-4" data-controller="vote">
    <div class="show-card-header mb-3">
      <h4 class=""><strong><%= decision.title %></strong></h4>
    </div>
    <div class="px-3">
      <p><%= decision.description %></p>
    <div class="mt-3">
        <div class="vote-buttons gap-5 waiting-for-vote"
              id="<%= dom_id(decision) %>">
          <%= button_to 'Pour', vote_decision_path(decision, vote_value: 'for'),
                data: { turbo_method: :post },
                class: 'rectangle justify-content-center mb-5'
          %>
          <%= button_to 'Contre', vote_decision_path(decision, vote_value: 'against'),
                data: { turbo_method: :post },
                class: 'rectangle justify-content-center'
          %>
        </div>
        <div id="<%= dom_id(decision) %>_result" >
        </div>
        <div class="d-flex  justify-content-end mt-3">
          <% if decision.opened?%>
            <%= link_to "Clôturer le vote", close_decision_path(decision),
              class: "show-btn d-none",
              data: {
                turbo_method: :patch,
                meeting_target: "adminBtn"
              }
            %>
          <% end %>
        </div>
    </div>
    </div>
  </div>
</div>
</div>

app/views/decisions/edit.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class = "card border-0 rounded shadow-lg p-4" style="max-width: 700px; width: 100%;">

  <h2 class="text-center" style = "color: #595959;">Modifier votre decision</h2>
    <%= simple_form_for [@meeting, @decision] do |f| %>
      <div class="form-group mb-3">
        <%= f.input :description, label: "Description" %>
      </div>
      <div class="d-flex justify-content">
        <%= f.submit "Submit", class: "button-card" %>
      </div>
    <% end %>
  </div>
</div>

app/views/decisions/index.html.erb
<h1>A vos votes!</h1>
<div class="cards-container">
  <div class="row">
    <% @decisions.each do |decision| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= decision.description %></h5>
            <p class="card-text">Statut: <%= decision.status %></p>

            <div class="d-flex gap-2">
              <%= link_to "Pour", decision_votes_path(@decision, value: true), data: { turbo_method: :post }, class: "btn btn-success" %>
              <%= link_to "Contre", decision_votes_path(@decision, value: false), data: { turbo_method: :post }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/decisions/new.html.erb
<div class="container document-container">
  <div class="document-card">
   <div class="document-body">
     <div class="row">
      <div class="col">
        <%= simple_form_for [@meeting, @decision] do |f| %>
            <%= f.input :title, label: "Titre" %>
          </div>
          <div class="decison-card-body">
            <%= f.input :description, label: "Description" %>
          </div>
          <div class="decison-card-body">
            <%= f.input :file, as: :file, label: "Document" %>
          </div>
          <div class="decison-card-body">
            <%= f.input :document_name, label: "Nom document" %>
          </div>
          <div class="decison-card-body">
            <%= f.input :document_tag, label: "Tag document" %>
          </div>
          <div class="document-submit-container">
              <%= f.submit "Submit", class: "secondary-btn secondary-btn:hover" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/decisions/show.html.erb
<div class="container document-container">
  <div class="document-card">
   <div class="document-body">
    <p><strong>Titre :</strong> <%= @decision.title %></p>
    <p><strong>Description :</strong> <%= @decision.description %></p>
    <p><strong>Statut :</strong> <%= @decision.status %></p>

    <p><%= link_to "Ajouter un document", new_decision_document_path(@decision), class:"secondary-btn "%></p>
    <p><%= link_to 'Modifier', edit_decision_path(@decision), class:"secondary-btn "%></p>
    <p><%= link_to 'Retour au meeting', meeting_path(@decision.meeting), class:"primary-btn " %></p>
  </div>

      <% if @decision.documents.any? %>
        <% @decision.documents.each do |document| %>
         <div class = "document-body">
          <%= cl_image_tag document.file.key, class:"d-block w-100" %>
        </div>
        <% end %>
      <% end %>
  </div>
  </div>

app/views/decisions/vote.html.erb
<% total_votes = @decision.votes.count.to_f %>
<% pourcentage_pour = total_votes.zero? ? 0 : ((@decision.votes.where(value: true).count / total_votes) * 100).round %>
<% pourcentage_contre = total_votes.zero? ? 0 : ((@decision.votes.where(value: false).count / total_votes) * 100).round %>

<% if @decision.already_voted_by?(current_user) || @decision.closed? %>
  <div data-vote-target="voteSection">
    <div><span></span> <span><%= @decision.votes.where(value: true).count %></span> pour</div>
    <div><span></span> <span><%= @decision.votes.where(value: false).count %></span> contre</div>
  </div>

  <div class="progress mt-2">
    <div class="progress-bar bg-success" role="progressbar"
         style="width: <%= pourcentage_pour %>%;"
         aria-valuenow="<%= pourcentage_pour %>"
         aria-valuemin="0"
         aria-valuemax="100">
      <%= pourcentage_pour %>% Pour
    </div>
    <div class="progress-bar bg-danger" role="progressbar"
         style="width: <%= pourcentage_contre %>%;"
         aria-valuenow="<%= pourcentage_contre %>"
         aria-valuemin="0"
         aria-valuemax="100">
      <%= pourcentage_contre %>% Contre
    </div>
  </div>

  <div class="d-flex gap-2 mt-2">
    <% if @decision.vote_of(current_user).value %>
      <span class="text-success">✅ Vous avez voté "pour".</span>
    <% else %>
      <span class="text-danger">❌ Vous avez voté "contre".</span>
    <% end %>
  </div>

<% else %>
  <div class="d-flex gap-2 mt-2">
    <%= link_to "Pour", decision_votes_path(@decision, value: true), data: { turbo_method: :post }, class: "btn btn-success" %>
    <%= link_to "Contre", decision_votes_path(@decision, value: false), data: { turbo_method: :post }, class: "btn btn-danger" %>
  </div>
<% end %>

<% if current_user.status == true && @decision.opened? %>
  <%= link_to "Clôturer le vote", close_decision_path(@decision), class: "btn btn-primary", data: { turbo_method: :patch } %>
<% end %>


<% if @decision.closed? %>
  <div data-vote-target="resultSection" class="mt-3">
    <% total_pour = @decision.for%>
    <% total_contre = @decision.against %>

    <% if total_pour > total_contre %>
      <p>La majorité a voté <strong>"Pour"</strong> avec <%= total_pour %> votes.</p>
    <% elsif total_contre > total_pour %>
      <p>La majorité a voté <strong>"Contre"</strong> avec <%= total_contre %> votes.</p>
    <% else %>
      <p>Il y a une égalité avec <%= total_pour %> votes "Pour" et <%= total_contre %> votes "Contre".</p>
    <% end %>
  </div>
<% end %>

app/views/decisions/vote.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@decision)) do %>
  <% if @decision.vote_of(current_user).value %>
    <h3 class="text">✅ Vous avez voté "pour".</h3>
  <% else %>
    <h3 class="text">✅ Vous avez voté "contre".</h3>
  <% end %>

  <p><em>Le vote est toujours en cours</em></p>

  <%#= render "decisions/result", decision: @decision %>
<% end %>