config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get :floors, to: "pages#floors"
  get :user_infos, to: "pages#user_infos"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meetings, only: [:index, :new, :create, :show, :update, :edit] do
    resources :decisions, only: [:new, :create, :index]
    resources :documents, only: [:new, :create, :index, :show]
    member do
      get :show_pdf
    end
  end

  resources :decisions, only: [:show, :update, :edit] do
    member do
      post :vote
      patch :open
      patch :close
    end

    resources :documents, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :documents, only: [:index, :show, :new, :create]

  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :chat_members, only: [:create]
    resources :messages, only: [:create]
  end
end

app/views/shared/_appartment_user_infos.html.erb
<div class="user-infos bg-white mb-2 p-3 rounded-4 shadow-sm user-infos bounce-in-top">
  <div class="d-flex gap-2">
    <%= cl_image_tag user.photo.key, width: 75, height: 75, q_auto: "eco" %>
    <div class="flex-grow-1">
      <p class="fs-5"><%= user.first_name %> <%= user.last_name %></p>
      <p class="mb-3 opacity-50"><%= user.email %></p>
      <% unless current_user == user %>
        <div class="d-flex justify-content-end">
          <% chatroom = current_user.chatroom_with(user) %>
          <%= link_to "Contacter", chatroom_path(chatroom), class: "show-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_floor_1.html.erb
<svg width="298" height="424" viewBox="0 0 298 424" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path id="app_1" data-floor-target="appartment" data-action="click->floor#change" d="M11.8872 11.4233H240.226C265.542 11.4233 286.065 31.9462 286.065 57.2625V172.686H11.8872V11.4233Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_2" data-floor-target="appartment" data-action="click->floor#change" d="M154.812 238.48L285.937 238.43L285.965 309.182C285.986 359.992 244.812 401.198 194.002 401.217L154.877 401.232L154.812 238.48Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_3" data-floor-target="appartment" data-action="click->floor#change" d="M11.8872 177.411H286.065V232.122H11.8872V177.411Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <mask id="path-4-inside-1_283_553" fill="white">
    <path d="M92.7086 400.905C92.7077 402.009 91.8114 402.904 90.7069 402.903L75.8297 402.89C39.3789 402.857 9.85588 373.281 9.88813 336.83L9.97653 236.922L92.8537 236.997L92.7086 400.905Z"/>
  </mask>
  <path id="app_4" data-floor-target="appartment" data-action="click->floor#change" d="M92.7086 400.905C92.7077 402.009 91.8114 402.904 90.7069 402.903L75.8297 402.89C39.3789 402.857 9.85588 373.281 9.88813 336.83L9.97653 236.922L92.8537 236.997L92.7086 400.905Z" fill="white" stroke="#358F80" stroke-width="8" mask="url(#path-4-inside-1_283_553)"/>
  <path d="M5.84555 5.5H219.607C259.647 5.5 292.107 37.9594 292.107 78V305.707C292.107 361.211 247.111 406.207 191.607 406.207H78.3456C38.305 406.207 5.84555 373.747 5.84555 333.707V5.5Z" stroke="black" stroke-width="11"/>
  <path d="M137.434 151.256L139.283 147.717L140.169 148.18L140.207 148.107L140.245 148.18L141.131 147.717L142.98 151.256L142.093 151.719L143.942 155.259L144.828 154.796L146.677 158.336L145.79 158.799L147.639 162.339L148.525 161.876L150.374 165.415L149.488 165.878L151.336 169.418L152.223 168.955L154.071 172.495L153.185 172.958L153.345 173.265H153.147V174.265H149.45V173.265H145.753V174.265H142.055V173.265H138.358V174.265H134.661V173.265H130.964V174.265H127.267V173.265H127.069L127.229 172.958L126.342 172.495L128.191 168.955L129.077 169.418L130.926 165.878L130.04 165.415L131.888 161.876L132.775 162.339L134.623 158.799L133.737 158.336L135.585 154.796L136.472 155.259L138.32 151.719L137.434 151.256Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M177.789 294.754L181.441 296.5L181.01 297.402L181.029 297.411L181.01 297.421L181.473 298.308L177.886 300.177L177.423 299.29L173.837 301.16L174.299 302.047L170.713 303.916L170.25 303.029L166.663 304.898L167.126 305.785L163.54 307.655L163.077 306.768L159.49 308.637L159.953 309.524L156.366 311.393L155.904 310.506L155.544 310.694L155.541 310.503L154.541 310.52L154.476 306.905L155.476 306.888L155.412 303.273L154.412 303.29L154.347 299.675L155.347 299.658L155.282 296.043L154.283 296.06L154.218 292.444L155.218 292.427L155.153 288.812L154.154 288.829L154.089 285.214L155.089 285.197L155.086 285.007L155.452 285.182L155.882 284.279L159.534 286.025L159.103 286.927L162.754 288.673L163.185 287.771L166.836 289.517L166.405 290.419L170.056 292.165L170.487 291.263L174.138 293.009L173.707 293.911L177.359 295.656L177.789 294.754Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M69.1703 309.887L65.5463 308.088L65.9909 307.193L65.9722 307.183L65.9908 307.174L65.5417 306.281L69.1566 304.464L69.6057 305.357L73.2205 303.541L72.7714 302.647L76.3863 300.831L76.8354 301.724L80.4502 299.907L80.0011 299.014L83.616 297.197L84.0651 298.091L87.68 296.274L87.2308 295.381L90.8457 293.564L91.2948 294.457L91.6572 294.275L91.6577 294.466L92.6577 294.464L92.6669 298.079L91.6669 298.082L91.6761 301.697L92.6761 301.695L92.6852 305.311L91.6853 305.313L91.6944 308.929L92.6944 308.926L92.7036 312.542L91.7036 312.545L91.7128 316.16L92.7128 316.158L92.722 319.774L91.722 319.776L91.7224 319.967L91.3591 319.786L90.9145 320.682L87.2905 318.883L87.7351 317.987L84.111 316.188L83.6665 317.084L80.0424 315.285L80.487 314.389L76.863 312.59L76.4184 313.486L72.7944 311.687L73.2389 310.791L69.6149 308.992L69.1703 309.887Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M48.3397 210.071L50.1883 206.531L51.0747 206.994L51.1125 206.921L51.1504 206.994L52.0368 206.531L53.8854 210.071L52.999 210.534L54.8476 214.074L55.734 213.611L57.5826 217.15L56.6961 217.613L58.5447 221.153L59.4311 220.69L61.2797 224.23L60.3933 224.693L62.2419 228.233L63.1283 227.77L64.9769 231.309L64.0904 231.772L64.2508 232.079H64.0526V233.079H60.3554V232.079H56.6583V233.079H52.9611V232.079H49.264V233.079H45.5668V232.079H41.8697V233.079H38.1725V232.079H37.9743L38.1346 231.772L37.2482 231.309L39.0968 227.77L39.9832 228.233L41.8318 224.693L40.9454 224.23L42.794 220.69L43.6804 221.153L45.5289 217.613L44.6425 217.15L46.4911 213.611L47.3775 214.074L49.2261 210.534L48.3397 210.071Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <g filter="url(#filter0_d_283_553)">
    <rect x="97.887" y="236.71" width="50.4868" height="178.621" fill="#D9D9D9"/>
  </g>
  <defs>
    <filter id="filter0_d_283_553" x="93.887" y="236.71" width="58.4868" height="186.621" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feFlood flood-opacity="0" result="BackgroundImageFix"/>
      <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
      <feOffset dy="4"/>
      <feGaussianBlur stdDeviation="2"/>
      <feComposite in2="hardAlpha" operator="out"/>
      <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
      <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_283_553"/>
      <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_283_553" result="shape"/>
    </filter>
  </defs>
</svg>

app/views/shared/_floor_2.html.erb
<svg width="401" height="558" viewBox="0 0 401 558" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path id="app_5" data-floor-target="appartment" data-action="click->floor#change" d="M16 236H386V397H16V236Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_6" data-floor-target="appartment" data-action="click->floor#change" d="M179.953 15.5021L16.0689 16.0312L16.7242 228.531L180.609 228.002L179.953 15.5021Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_7" data-floor-target="appartment" data-action="click->floor#change" d="M17.3392 408.143L386.023 407.995L386.034 435.364C386.053 486.174 344.879 527.381 294.069 527.401L108.385 527.475C58.1271 527.496 17.3693 486.77 17.35 436.512L17.3392 408.143Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_8" data-floor-target="appartment" data-action="click->floor#change" d="M194 16H322C357.346 16 386 44.6538 386 80V229H194V16Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <line y1="-2.5" x2="118.711" y2="-2.5" transform="matrix(0.00138374 0.999999 -0.999999 0.00144908 174.429 407.55)" stroke="#358F80" stroke-width="5"/>
  <line y1="-2.5" x2="118.711" y2="-2.5" transform="matrix(0.00138374 0.999999 -0.999999 0.00144908 106.853 407.565)" stroke="#358F80" stroke-width="5"/>
  <path d="M351.707 197.512L353.569 193.837L354.461 194.289L354.5 194.213L354.539 194.289L355.431 193.837L357.293 197.512L356.401 197.964L358.263 201.639L359.155 201.188L361.017 204.863L360.125 205.314L361.987 208.989L362.879 208.538L364.741 212.212L363.849 212.664L365.711 216.339L366.603 215.888L368.465 219.562L367.573 220.014L369.435 223.689L370.327 223.238L372.189 226.913L371.297 227.364L371.492 227.75H371.258V228.75H367.534V227.75H363.81V228.75H360.086V227.75H356.362V228.75H352.638V227.75H348.914V228.75H345.19V227.75H341.466V228.75H337.742V227.75H337.508L337.703 227.364L336.811 226.913L338.673 223.238L339.565 223.689L341.427 220.014L340.535 219.562L342.397 215.887L343.289 216.339L345.151 212.664L344.259 212.212L346.121 208.537L347.013 208.989L348.875 205.314L347.983 204.862L349.845 201.188L350.737 201.639L352.599 197.964L351.707 197.512Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M45.7071 197.512L47.569 193.837L48.4611 194.289L48.5 194.213L48.5389 194.289L49.431 193.837L51.2929 197.512L50.4009 197.964L52.2628 201.639L53.1549 201.188L55.0168 204.863L54.1248 205.314L55.9868 208.989L56.8788 208.538L58.7407 212.212L57.8487 212.664L59.7107 216.339L60.6027 215.888L62.4647 219.562L61.5726 220.014L63.4346 223.689L64.3266 223.238L66.1886 226.913L65.2965 227.364L65.4919 227.75H65.2576V228.75H61.5337V227.75H57.8098V228.75H54.0859V227.75H50.362V228.75H46.638V227.75H42.9141V228.75H39.1902V227.75H35.4663V228.75H31.7424V227.75H31.5081L31.7035 227.364L30.8114 226.913L32.6734 223.238L33.5654 223.689L35.4274 220.014L34.5353 219.562L36.3973 215.887L37.2893 216.339L39.1513 212.664L38.2593 212.212L40.1212 208.537L41.0132 208.989L42.8752 205.314L41.9832 204.862L43.8451 201.188L44.7372 201.639L46.5991 197.964L45.7071 197.512Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M45.7071 197.512L47.569 193.837L48.4611 194.289L48.5 194.213L48.5389 194.289L49.431 193.837L51.2929 197.512L50.4009 197.964L52.2628 201.639L53.1549 201.188L55.0168 204.863L54.1248 205.314L55.9868 208.989L56.8788 208.538L58.7407 212.212L57.8487 212.664L59.7107 216.339L60.6027 215.888L62.4647 219.562L61.5726 220.014L63.4346 223.689L64.3266 223.238L66.1886 226.913L65.2965 227.364L65.4919 227.75H65.2576V228.75H61.5337V227.75H57.8098V228.75H54.0859V227.75H50.362V228.75H46.638V227.75H42.9141V228.75H39.1902V227.75H35.4663V228.75H31.7424V227.75H31.5081L31.7035 227.364L30.8114 226.913L32.6734 223.238L33.5654 223.689L35.4274 220.014L34.5353 219.562L36.3973 215.887L37.2893 216.339L39.1513 212.664L38.2593 212.212L40.1212 208.537L41.0132 208.989L42.8752 205.314L41.9832 204.862L43.8451 201.188L44.7372 201.639L46.5991 197.964L45.7071 197.512Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M78.8493 469.077L75.2499 467.147L75.722 466.266L75.6089 466.205L75.7232 466.147L75.2691 465.256L78.9069 463.403L79.3611 464.294L82.9989 462.441L82.5447 461.55L86.1825 459.697L86.6367 460.588L90.2745 458.735L89.8203 457.844L93.4582 455.991L93.9123 456.883L97.5502 455.03L97.096 454.139L100.734 452.286L101.188 453.177L104.826 451.324L104.372 450.433L108.009 448.58L108.464 449.471L108.812 449.294L108.809 449.534L109.809 449.545L109.771 453.327L108.771 453.317L108.733 457.099L109.732 457.11L109.694 460.893L108.694 460.882L108.656 464.665L109.656 464.675L109.617 468.458L108.617 468.447L108.579 472.23L109.579 472.24L109.541 476.023L108.541 476.012L108.502 479.795L109.502 479.806L109.464 483.588L108.464 483.577L108.462 483.818L108.117 483.633L107.645 484.515L104.046 482.585L104.518 481.704L100.918 479.774L100.446 480.655L96.8467 478.725L97.3188 477.844L93.7194 475.914L93.2472 476.796L89.6477 474.866L90.1199 473.985L86.5204 472.055L86.0483 472.936L82.4488 471.006L82.921 470.125L79.3215 468.195L78.8493 469.077Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M202.768 358.327L206.399 360.194L205.942 361.084L206.056 361.142L205.943 361.202L206.412 362.086L202.805 364.001L202.336 363.118L198.73 365.034L199.199 365.917L195.592 367.833L195.123 366.95L191.517 368.866L191.986 369.749L188.379 371.665L187.91 370.782L184.304 372.698L184.773 373.581L181.166 375.497L180.697 374.614L177.091 376.53L177.56 377.413L173.953 379.329L173.484 378.446L173.139 378.629L173.138 378.389L172.138 378.396L172.113 374.613L173.113 374.606L173.089 370.823L172.089 370.83L172.064 367.047L173.064 367.041L173.04 363.258L172.04 363.265L172.015 359.482L173.015 359.475L172.991 355.692L171.991 355.699L171.966 351.916L172.966 351.91L172.942 348.127L171.942 348.134L171.917 344.351L172.917 344.344L172.915 344.104L173.263 344.282L173.72 343.393L177.351 345.26L176.894 346.149L180.525 348.016L180.982 347.127L184.613 348.993L184.156 349.883L187.787 351.75L188.244 350.86L191.875 352.727L191.418 353.616L195.049 355.483L195.506 354.594L199.137 356.461L198.68 357.35L202.311 359.217L202.768 358.327Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M205.586 463.014L209.195 464.927L208.727 465.81L208.84 465.87L208.726 465.929L209.184 466.818L205.555 468.689L205.097 467.8L201.468 469.67L201.926 470.559L198.297 472.43L197.838 471.541L194.209 473.411L194.668 474.3L191.039 476.171L190.58 475.282L186.951 477.153L187.409 478.042L183.78 479.912L183.322 479.023L179.693 480.894L180.151 481.783L176.522 483.653L176.064 482.765L175.716 482.944L175.718 482.703L174.718 482.697L174.738 478.915L175.738 478.92L175.759 475.138L174.759 475.132L174.78 471.349L175.78 471.355L175.801 467.572L174.801 467.566L174.821 463.784L175.821 463.789L175.842 460.007L174.842 460.001L174.863 456.218L175.863 456.224L175.883 452.441L174.884 452.435L174.904 448.653L175.904 448.658L175.906 448.418L176.251 448.601L176.719 447.717L180.327 449.63L179.859 450.513L183.468 452.425L183.936 451.542L187.544 453.454L187.076 454.337L190.684 456.25L191.152 455.366L194.761 457.278L194.293 458.162L197.901 460.074L198.369 459.19L201.978 461.102L201.51 461.986L205.118 463.898L205.586 463.014Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <g filter="url(#filter0_d_283_554)">
    <rect x="111" y="316" width="64" height="234" fill="#D9D9D9"/>
  </g>
  <path d="M5.5 5.5H323C363.041 5.5 395.5 37.9594 395.5 78V435C395.5 490.505 350.505 535.5 295 535.5H106C50.4954 535.5 5.5 490.505 5.5 435V5.5Z" stroke="black" stroke-width="11"/>
  <defs>
    <filter id="filter0_d_283_554" x="107" y="316" width="72" height="242" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feFlood flood-opacity="0" result="BackgroundImageFix"/>
      <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
      <feOffset dy="4"/>
      <feGaussianBlur stdDeviation="2"/>
      <feComposite in2="hardAlpha" operator="out"/>
      <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
      <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_283_554"/>
      <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_283_554" result="shape"/>
    </filter>
  </defs>
</svg>

app/views/shared/_floor_3.html.erb
<svg width="404" height="592" viewBox="0 0 404 592" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path id="app_9" data-floor-target="appartment" data-action="click->floor#change"  d="M14.285 241.147L386.943 241.001L387.029 461.268C387.049 510.422 347.218 550.284 298.064 550.303L105.406 550.379C55.1482 550.398 14.3902 509.672 14.3705 459.414L14.285 241.147Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path id="app_10" data-floor-target="appartment" data-action="click->floor#change"  d="M14 15H326C359.689 15 387 42.3106 387 76V239H14V15Z" fill="white" stroke="#358F80" stroke-width="4"/>
  <path d="M64.0122 205.85L66.0041 201.95L66.8946 202.405L67 202.199L67.1054 202.405L67.9959 201.95L69.9878 205.85L69.0972 206.305L71.0891 210.205L71.9796 209.75L73.9715 213.65L73.0809 214.105L75.0728 218.005L75.9634 217.55L77.9552 221.45L77.0647 221.905L79.0565 225.805L79.9471 225.35L81.9389 229.25L81.0484 229.705L83.0402 233.605L83.9308 233.15L85.9227 237.05L85.0321 237.505L85.285 238H84.9267V239H80.943V238H76.9593V239H72.9756V238H68.9919V239H65.0081V238H61.0244V239H57.0407V238H53.057V239H49.0733V238H48.715L48.9679 237.505L48.0773 237.05L50.0692 233.15L50.9598 233.605L52.9516 229.705L52.0611 229.25L54.0529 225.35L54.9435 225.805L56.9353 221.905L56.0448 221.45L58.0366 217.55L58.9272 218.005L60.9191 214.105L60.0285 213.65L62.0204 209.75L62.9109 210.205L64.9028 206.305L64.0122 205.85Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <path d="M190.464 373.435L194.356 375.443L193.898 376.332L194.104 376.438L193.897 376.542L194.348 377.435L190.44 379.411L189.989 378.519L186.081 380.495L186.533 381.387L182.625 383.364L182.173 382.471L178.265 384.447L178.717 385.34L174.809 387.316L174.357 386.424L170.45 388.4L170.901 389.292L166.993 391.269L166.542 390.376L162.634 392.352L163.085 393.245L159.177 395.221L158.726 394.329L158.23 394.58L158.231 394.221L157.231 394.217L157.247 390.234L158.247 390.238L158.263 386.254L157.263 386.25L157.279 382.266L158.279 382.27L158.295 378.287L157.295 378.283L157.311 374.299L158.311 374.303L158.326 370.319L157.326 370.315L157.342 366.332L158.342 366.336L158.358 362.352L157.358 362.348L157.374 358.364L158.374 358.368L158.376 358.01L158.87 358.265L159.328 357.376L163.22 359.384L162.762 360.272L166.654 362.28L167.112 361.391L171.004 363.398L170.546 364.287L174.438 366.295L174.896 365.406L178.788 367.413L178.33 368.302L182.222 370.309L182.68 369.421L186.572 371.428L186.114 372.317L190.006 374.324L190.464 373.435Z" stroke="#358F80" stroke-width="2" stroke-dasharray="4 4"/>
  <g filter="url(#filter0_d_283_555)">
  <rect x="90" y="338" width="68" height="246" fill="#D9D9D9"/>
  </g>
  <path d="M5.5 5.5H326C366.041 5.5 398.5 37.9594 398.5 78V459C398.5 514.505 353.505 559.5 298 559.5H106C50.4954 559.5 5.5 514.505 5.5 459V5.5Z" stroke="black" stroke-width="11"/>
  <defs>
    <filter id="filter0_d_283_555" x="86" y="338" width="76" height="254" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feFlood flood-opacity="0" result="BackgroundImageFix"/>
      <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
      <feOffset dy="4"/>
      <feGaussianBlur stdDeviation="2"/>
      <feComposite in2="hardAlpha" operator="out"/>
      <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
      <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_283_555"/>
      <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_283_555" result="shape"/>
    </filter>
  </defs>
</svg>

app/views/shared/_header.html.erb
<div class="header">
  <%= link_to root_path, class: "text-decoration-none" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <h5 style = "text-align: justify; padding-right: 15px;"><em><%= title %></em></h5>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-navbar">
  <div class="container-fluid">

<%= link_to root_path, class: "navbar-icon #{'active' if current_page?(root_path)}" do %>
  <div class="icon-container">
    <i class="fa-solid fa-house" style= "color: #ffffff"></i>
  </div>
  <span class="icon-text">Acceuil</span>
<% end %>

<%= link_to documents_path, class: "navbar-icon #{'active' if current_page?(documents_path)}" do %>
  <div class="icon-container">
    <i class="fa-regular fa-file" style= "color:#ffffff"></i>
  </div>
  <span class="icon-text">Documents</span>
<% end %>

<%= link_to meetings_path, class: "navbar-icon #{'active' if current_page?(meetings_path)}" do %>
  <div class="icon-container">
    <i class="fa-regular fa-calendar" style= "color:#ffffff"></i>
  </div>
  <span class="icon-text">Réunions</span>
<% end %>

<%= link_to chatrooms_path, class: "navbar-icon #{'active' if current_page?(chatrooms_path)}" do %>
  <div class="icon-container position-relative">
    <i class="fa-regular fa-comments" style= "color:#ffffff"></i>
    <% if @unread_messages_counter.present? && @unread_messages_counter >= 1 %>
      <div class="pill pill-navbar"><%= @unread_messages_counter %></div>
    <% end %>
  </div>
  <span class="icon-text">Zenmates</span>
<% end %>

<%= link_to "#", class: "navbar-icon" do %>
  <div class="navbar-avatar">
    <% if user_signed_in? && current_user.status? %>
      <i class="fa-solid fa-crown text-yellow"></i>
      <%= cl_image_tag current_user.photo.key, width: 32, height: 32%>
    <% elsif user_signed_in? && !current_user.status?%>
      <%= cl_image_tag current_user.photo.key, width: 32, height: 32%>
    <% else %>
    
      <i class="fa-regular fa-user"></i>
    <% end %>
  </div>
  <span class="icon-text">Profil</span>
<% end %>
</div>
</div>

app/views/shared/_primary_button.html.erb
<%= link_to text, path, class: "primary-btn" %>