config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get :floors, to: "pages#floors"
  get :user_infos, to: "pages#user_infos"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meetings, only: [:index, :new, :create, :show, :update, :edit] do
    resources :decisions, only: [:new, :create, :index]
    resources :documents, only: [:new, :create, :index, :show]
    member do
      get :show_pdf
    end
  end

  resources :decisions, only: [:show, :update, :edit] do
    member do
      post :vote
      patch :open
      patch :close
    end

    resources :documents, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :documents, only: [:index, :show, :new, :create]

  resources :chatrooms, only: [:index, :show, :new, :create] do
    resources :chat_members, only: [:create]
    resources :messages, only: [:create]
  end
end

app/views/pages/floors.html.erb
<div class="container" data-controller="floor">
  <div class="floor-map overflow-hidden">
    <div class="d-flex floor-map-svgs" data-floor-target="floorsContainer">
      <div class="d-flex justify-content-center w-100">
        <%= render "shared/floor_1" %>
      </div>
      <div class="d-flex justify-content-center w-100">
        <%= render "shared/floor_2" %>
      </div>
      <div class="d-flex justify-content-center w-100">
        <%= render "shared/floor_3" %>
      </div>
    </div>
    <div class="d-flex align-items-center justify-content-center gap-4 mb-2 mt-2">
      <i class="fa-solid fa-angle-left" data-action="click->floor#previousFloor"></i>
      <span class="fs-4 text-center">Étage <span data-floor-target="floorNumber" style="width: 1rem; display: inline-block">1</span></span>
      <i class="fa-solid fa-angle-right" data-action="click->floor#nextFloor"></i>
    </div>
  </div>
  <% user = User.first %>
  <div data-floor-target="userInfosContainer">
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h4><strong>Mes prochaines réunions :</strong></h4>
  <br>
  <div class="row meeting-cards">
    <% @meetings.each do |meeting| %>
      <div class="col-9 col-sm-12 col-md-12">
        <div class="meeting-card">
          <div class="meeting-card-header flex-row justify-content-between align-items-center">
            <p style = "color: #ffffff" ><i><%= l(meeting.date, format: :long) %></i></p>
            <div class="d-flex justify-content-center align-items-center">
              <i class="fa-regular fa-clock me-2"></i>
              <p style = "color: #ffffff">18h</p>
            </div>
          </div>
          <%= link_to meeting_path(meeting) do %>
            <div class="py-3 px-2 meeting-card-body";>
              <p class="card-title" style="font-size: 16px;"><%= meeting.title %></p>
              <p style="font-size: 15px;" class="card-text"><em><%= meeting.description %></em></p>
            </div>
          <% end %>
          <div class ="card-text-icone ps-2">
            <button type="button" class="modal-btn p-0" data-bs-toggle="modal" data-bs-target="#exampleModal">
              <i class="fa-solid fa-plus" style="font-size: 15px; color: #fe6363;"></i> <span style="margin-left: 4px; font-size: 16px; color:rgb(71, 67, 67);">Ajouter des décisions</span>
            </button>
            <br>
            <%= link_to meeting_documents_path(meeting) do %>
              <i class="fa-regular fa-eye" style="font-size: 15px; color: #fe6363;"></i> <span style="pe-2 font-size: 15px;"> Accéder aux documents</span>
            <% end %>
          </div>
        </div>

        <%= render "decisions/form", meeting: meeting, decision: @decision %>
      </div>

    <% end %>
  </div>
  <br>
  <h4><strong>Mes actualités :</strong></h4>
  <br>

  <div>
    <% if @unread_messages_counter.present? && @unread_messages_counter > 0 %>
      <%= link_to chatrooms_path, class: "text-decoration-none d-flex mb-1"  do %>
        <div class="document-affichage" style="margin-bottom:10px;">
          <div class="document-icon">
            <i class="fa-regular fa-comments"></i>
          </div>
          <div class="document-name">
            <p><%= @unread_messages_counter %> <%= @unread_messages_counter > 1 ? "nouveaux messages" : "nouveau message" %></p>
          </div>
        </div>
      <% end %>
    <% end %>


  <% if current_user %>
    <% documents = current_user.coproperty.documents.where("created_at > ?", Date.current) %>
    <% if documents.any? %>
      <% documents.each do |document| %>
        <%= link_to document_path(document), class: "text-decoration-none d-flex mb-1"  do %>
          <div class="document-affichage" style="margin-bottom:10px;">
            <div class="document-icon">
              <i class="fa-regular fa-file"></i>
            </div>
            <div class="document-name text-decoration-none d-flex justify-content-between">
              <p> <%= document.name %> </p>
              <p style="font-size: 13px;"><%= document.created_at.strftime('%d/%m/%Y') %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  </div>
  <div>
    <%=link_to "Plan de l'immeuble", floors_path, class: "btn building-btn" %>
    </div>
</div>